### ISSUE TITLE
readme에 적힌 제품키는 노출이 되어도 문제없나요? 앞자리가 없어서...?

### ISSUE THREAD

**Issue by khw7096** [lazypic/install-maya-centos#3]
그냥 궁금해서 물어봐용.

**Comment by kohyuk91** [comment]
@khw7096 
https://knowledge.autodesk.com/ko/customer-service/download-install/activate/find-serial-number-product-key/product-key-look/2018-product-keys

아 '제품키'는 '시리얼넘버' 랑은 다른 거여서 이런식으로 매년 사이트에 공개해요 :)

**Comment by khw7096** [comment]
아항.

**Comment by khw7096** [comment]
진행과정을 보고 있는데 마야는 설치 장난아니네용.
